name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Checkout é importante para garantir que o ambiente tenha acesso ao repositório
      - uses: actions/checkout@v4

 - uses: Platane/snk@v3
        with:
          github_user_name: samiraevangelista
          outputs: |
            # Isso gera a versão dark que você já está usando, focada no seu histórico total
            dist/github-contribution-grid-snake-dark.svg?color_snake=#d8b4fe&color_dots=#0d1117,#3f3f46,#71717a,#a855f7,#d8b4fe


    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


